# Generated by Django 3.2.12 on 2022-03-02 07:42

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0002_hospitalpatient_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalpatient',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelManagers(
            name='hospitalpatient',
            managers=[
                ('draft', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='hospitalpatient',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitalpatient',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
