# Generated by Django 4.0.2 on 2022-02-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
