# Generated by Django 4.0.2 on 2022-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hu_tr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
